server {
    listen 80;

    location /auth/ {
        proxy_pass http://auth-service:3001/;
    }

    location /donor/ {
        proxy_pass http://service-2:80/;
    }

    location /history/ {
        proxy_pass http://service-3:3003/;
    }
}