limit_req_zone $binary_remote_addr zone=mylimit:10m rate=60r/m;

server {
    listen 80;

    limit_req (zone=mylimit burst=10 nodelay);

    location /auth/ {
        rewrite ^/auth/(.*) /$1 break;
        proxy_pass http://auth-service:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /donor/ {
        proxy_pass http://service-2:80; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    error_page 503 = @ratelimit;
    location @ratelimit {
        return 429 '{"status": "error", "message": "Sabar, jangan spam! Maksimal 60 req/menit."}';
    }
}